main: de.jojojux.ptlweekly.PlayerTimeLimit
version: 1.6.1
name: PlayerTimeLimit
api-version: 1.13
author: JoJoJux (orig. Ajneb97)
softdepend: [Multiverse-Core,PlaceholderAPI]

commands:
  playertimelimit:
    description: Main command of PlayerTimeLimit
    aliases: [ptl]